### ISSUE TITLE
no module named is13.data

### ISSUE THREAD

**Issue by lucas0** [mesnilgr/is13#11]
I've seen different issue reports from other people but they couldn't help me. I'm using windows now and no matter how I try, it seems I can't fix this, even with the path added to my environment variables. I've tried adding the is13 path in most different ways without success. I always end up getting "no module named is13.data" when try to run any of the two examples. Can someone help me? Thanks.

**Comment by mesnilgr** [comment]
@lucas0 a quick fix for that would be to:
- move every file from the directories to the same directory, e.g. the repo directory
- replace all the import e.g. `from is.data import ...` -> `from data import ...`

let me know if it works for you. I've actually never tried it on windows.

**Comment by lucas0** [comment]
I'm actually at my lab and trying to install it on a Mac, but as soon as I get home I'll try what you've said. Thank you for the fast answer, really appreciated it!

**Comment by lucas0** [comment]
Got to the same point on MacOS also. Did what you told me, also had to do the same thing on accuracy.py and passed that error (thanks!), but another one shows up now:

```
Lucass-MacBook-Pro:is13-master lucaslourenco$ python elman-forward.py 
Downloading data from http://www-etud.iro.umontreal.ca/~mesnilgr/atis/atis.fold3.pkl.gz
Traceback (most recent call last):
  File "elman-forward.py", line 30, in <module>
train_set, valid_set, test_set, dic = load.atisfold(s['fold'])
  File "/Users/lucaslourenco/Developer/is13-master/data/load.py", line 33, in atisfold
train_set, valid_set, test_set, dicts = cPickle.load(f)
  File "/Users/lucaslourenco/anaconda/lib/python2.7/gzip.py", line 268, in read
self._read(readsize)
  File "/Users/lucaslourenco/anaconda/lib/python2.7/gzip.py", line 303, in _read
self._read_gzip_header()
  File "/Users/lucaslourenco/anaconda/lib/python2.7/gzip.py", line 197, in _read_gzip_header
raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file
```

Any solutions to that?

**Comment by mesnilgr** [comment]
@lucas0 that's another problem. the university deleted my account where the data was stored. let me fix that and open another issue. thanks.
