### ISSUE TITLE
Some questions about the Dataset

### ISSUE THREAD

**Issue by lucas0** [mesnilgr/is13#15]
Hello,

it would be really useful to know what are the elements on the .pkl.

There are 3 "test_set", 3 "train_set" and 3 dictionaries inside "dicts":
- train/test_set[1] is full of 0's and I dont have a clue about what they mean, would someone explain me what those are? (Are those the weight
  weight for the "meanings" of the words or something like that???)
- train/test_set[2] is probably the array of IOB-labels, since it has plenty of '126',  and train/test_set[0] seems to be the word indexes arrays, because of the variety of numbers, right?
- dicts[0] is labels2idx, dict[2] is words2idx, but what is dicts[1], seems to??
- can I "invert" the dictionaries? Example: using labels2idx tuples "k : v"  to build idx2labels as "v : k"?

I know they are simple questions, and I'm sorry if I'm being inconvenient with all those questions, but please be patient with me, I'm new on deeplearning. Thank you.

**Comment by mesnilgr** [comment]
1) set[1] corresponds to Name entities. so there is a lot of zeros. check the paper to see what Name Entity means.
http://www.iro.umontreal.ca/%7Elisa/pointeurs/taslp_RNNSLU_final_doubleColumn.pdf
2) set[2] corresponds to labels and set[0] corresponds to word indexes
3) dicts[1] is the mapping to the Name Entity
4) inverting a dictionary can bed solved using a Google search. http://stackoverflow.com/questions/483666/python-reverse-inverse-a-mapping

**Comment by cbcase** [comment]
Hi Gregoire,

Do you happen to have the "intent" labels for the ATIS examples available somewhere? I'm interested in the joint utterance classification / slot-filling application. Thanks!

[I realize this isn't an "issue" per se, but it seemed the most appropriate place to ask. Also thanks for posting this code -- it's a great learning tool.]

**Comment by mesnilgr** [comment]
@cbcase Hi Carl, unfortunately Microsoft only let me release their version of the Slot-Filling dataset.

**Comment by cbcase** [comment]
Alright, thanks for the quick reply!

**Comment by 4poc** [comment]
For anyone looking as I was, you can find the intent labels for atis here (not sure if they are different to what you're talking about though):

https://github.com/hongyunnchen/JointSLU/tree/master/data
