### ISSUE TITLE
problems with --- python code/rnnslu.py

### ISSUE THREAD

**Issue by wendysalonika** [mesnilgr/is13#16]
Thank you really much for offering your code, i appreciate it 
(it's really helpful in order to understand rnns in slu - ive just started my master about them)

there are a couple of issues i've already dealt with in order to run rnnslu.py

I downloaded DeepLearningTutorials-master 
and in code/rnnslu.py i replaced atisfold() and load() and added download_dropbox()

and finally i got the right data  but now the error is 
 <<IndexError: index 557 is out of bounds for size 534>>
it is from function train() when   self.sentence_train(words, labels, learning_rate)

as i see  voc_size= 533  but here its trying to find the word id 557

SO: is it possible to upload sth that works without any errors?

---

(i tried to fix it myself, but then sth else came up and i thought maybe you could help)

thx in advance

**Comment by wendysalonika** [comment]
the error is 'IndexError'     index 557 is out of bounds for size 534

**Comment by mesnilgr** [comment]
I cannot reproduce your error. Can you try from a fresh update? (re-clone the repo and try again)

**Comment by wendysalonika** [comment]
then i guess im so 'lucky' that i have a problem out of nowhere
thnx for your time anyway
