### ISSUE TITLE
OSError: [Errno 2] No such file or directory: 'conlleval.pl'

### ISSUE THREAD

**Issue by lucas0** [mesnilgr/is13#17]
In OSX, after finishing training epoch 0 I get this error:

```
OSError: [Errno 2] No such file or directory: 'conlleval.pl'
```

**Comment by mesnilgr** [comment]
try from a fresh-start by re-cloning the repo. do you still have this problem?

**Comment by lucas0** [comment]
Yes.

I could manage to install numpy, scipy and theano correctly and I'm able to run Lasagne (https://github.com/Lasagne/Lasagne) examples, but still can't run your code.

From the fresh start this is what I did:

*clone repository
*put all .py in the same directory
*change the import statements on accuracy.py and elman-forward.py
*put the atis.pkl in the same folder

Then I call 

```
python elman-forward.py
```

and get this error

```
OSError: [Errno 2] No such file or directory: 'conlleval.pl'
```

**Comment by mesnilgr** [comment]
run `wget https://www.comp.nus.edu.sg/%7Ekanmy/courses/practicalNLP_2008/packages/conlleval.pl` in your code directory and re-run the experiment. let me know if it solves your problem.

**Comment by lucas0** [comment]
That`s worked, actually training epoch 2.! Thank you a lot for your attention, really appreciated that! 

I would like to ask you for one more thing: can you please give me a full description of the data set, i.e. answer those questions I've made on the other issue?

Thanks!
