### ISSUE TITLE
Get word embeddings aligned with words

### ISSUE THREAD

**Issue by usptact** [mesnilgr/is13#20]
Hi,

I would like to re-use the learned word embeddings (self.emb) in other experiments. It looks difficult to me to know what each word embedding (stored embeddings.npy) in the matrix corresponds to (words2idx dictionary). In addition there is an additional "word" which is used for padding.

My question is: how can I align the words with learned embeddings?

Thanks

**Comment by mesnilgr** [comment]
Hi,

```
e = numpy.load('embeddings.npy')
for word, index in words2idx.iteritems():
    print word, e[index]
```

the last line in the matrix `e[-1]` corresponds to the padding token.

**Comment by usptact** [comment]
Thank you! Works like a charm!

By the way, it turns out that we went to the same Université de Rouen ;)

**Comment by mesnilgr** [comment]
cool :) just graduated from there.
