### ISSUE TITLE
Cost function on last word in sentence

### ISSUE THREAD

**Issue by scrimshander** [mesnilgr/is13#21]
Apologies for what is more a theoretical question than a code issue, but I am new to RNNs and am using this code to learn. 

Why is the cost function based on the negative log likelihood of the last word in the sentence, rather than the mean of the NLLs of the entire sentence? I see this in line 53 of rnn/elman.py for examples.

Thanks in advance for the help as I learn.

**Comment by mesnilgr** [comment]
Both options are possible. We just obtained better performance using ''stochastic'' updates on the words only rather than using mini-batches. See Table 2 MB versus STO in the paper [here](http://www.iro.umontreal.ca/~lisa/pointeurs/taslp_RNNSLU_final_doubleColumn.pdf).

**Comment by scrimshander** [comment]
Thanks very much! I missed that in the paper.
