### ISSUE TITLE
rnnslu.py takes too longer than  40 seconds for nh=200

### ISSUE THREAD

**Issue by wendysalonika** [mesnilgr/is13#24]
as mentioned (on http://deeplearning.net/tutorial/rnnslu.html):
Running experiments on ATIS using this repository will run one epoch in less than 40 seconds

this must be for nh=100, right?
for nh=200 (at least for my pc) it takes about 3 times longer than for nh=100

--is that what it is supposed to be?
--how can we speed it up?

thanks in advance

**Comment by mesnilgr** [comment]
how long does it take on your pc to run with nh=100?
if it takes more than 40 seconds then check your Theano install.

complexity grows quadratically with nh. the way to speed that up would be to use sth different than Theano (one of the fastest being http://www.fit.vutbr.cz/~imikolov/rnnlm/)

**Comment by wendysalonika** [comment]
thanks for your response,
each epoch takes eg.35-39 for nh=100 secs
and for nh=200 the same epoch could be (about) 100 or even 120 secs

i was wondering if a GPU would help

**Comment by mesnilgr** [comment]
the code is not optimized for GPU but you may get a little speed-up.
you would have to integrate mini-batches in order to obtain a decent speed-up on GPU.

**Comment by wendysalonika** [comment]
thnx
I appreciate your help
