### ISSUE TITLE
A simple question about the ouput s_t of rnn

### ISSUE THREAD

**Issue by UniqueAndys** [mesnilgr/is13#26]
@mesnilgr @petrux @vierja  @stray-leone  
I have been reading the rnn code and I got an question in rnn/elman.py:
38--> def recurrence(x_t, h_tm1):
            h_t = T.nnet.sigmoid(T.dot(x_t, self.Wx) + T.dot(h_tm1, self.Wh) + self.bh)
            s_t = T.nnet.softmax(T.dot(h_t, self.W) + self.b)
            return [h_t, s_t]

```
    [h, s], _ = theano.scan(fn=recurrence, \
        sequences=x, outputs_info=[self.h0, None], \
        n_steps=x.shape[0])

    p_y_given_x_lastword = s[-1,0,:]
```

It defines a simple recurrent network and my question is what's the component of s_t? 
When we want to get p_y_given_x_lastword we use s[-1,0,:], "-1" means the lase element and ":" means
all, so why we use "0"? Because I think x_t and s_t is 1-d vector so why use index 0?
Could you solve this problem for me? Thank you very much.

**Comment by mesnilgr** [comment]
it outputs a 3D tensor with an axis with a single element.
it's a way to turn the 3D tensor into 2D.
