### ISSUE TITLE
Appying CRF after elman network

### ISSUE THREAD

**Issue by ankitKumarcsIITP** [mesnilgr/is13#27]
i wanted to  apply CRF over the RNN output of this repo  following http://research.microsoft.com/apps/pubs/default.aspx?id=210167  . I need to replace the softmax function with the crf classsification .But finding difficult to implement in the recurrence function. Any help is appreciated.

Thanks

**Comment by mesnilgr** [comment]
This is out of the scope of this repository. Good luck.

**Comment by ankitKumarcsIITP** [comment]
thanks anyway , hope to connect with u
