### ISSUE TITLE
README.md - miss

### ISSUE THREAD

**Issue by LEEKYOUNGHUN** [mesnilgr/is13#3]
README.md - bug

git clone git@github.com:mesnilgr/is13.git
cd is13
python examples/elman-forward.py

error 
Traceback (most recent call last):
  File "examples/elman-forward.py", line 9, in <module>
    from is13.rnn.elman import model
ImportError: No module named is13.rnn.elman

git clone git@github.com:mesnilgr/is13.git
python is13/examples/elman-forward.py

is no error

**Comment by mesnilgr** [comment]
fixed in https://github.com/mesnilgr/is13/commit/69422c47053831113fcd4b39b3edbd3ba1805a9f
thanks!
