### ISSUE TITLE
code bug

### ISSUE THREAD

**Issue by Helicqin** [mesnilgr/is13#30]
hi,@mesnilgr. i want to run the code:

```
import theano, numpy
from theano import tensor as T

# nv :: size of our vocabulary
# de :: dimension of the embedding space
# cs :: context window size

nv, de, cs = 1000, 50, 5
emb = theano.shared(0.2 * numpy.random.uniform(-1.0, 1.0, \
(nv+1, de)).astype(theano.config.floatX)) # add one for PADDING at the end
idxs = T.imatrix() # as many columns as words in the context window and as many lines as words in the sentence
x = self.emb[idxs].reshape((idxs.shape[0], de*cs))
```
but errors happened in emb[idxs].i do not understand why emb[idxs] is correct?i think emb is a matrix,idxs is also a matrix.So why?

I would appreciate it if you could give me some tips.
thanks.

**Comment by Wayne-Yuan** [comment]
Firstly, you should delete `self` from `self.emb[idxs]`.
Secondly, given `idxs` of shape [len_of_words, cs], `emb[idxs]` is of shape [len_of_words, cs, de], hence reshaping changes the shape to [len_of_words, cs*de],

**Comment by mesnilgr** [comment]
Thanks @Wayne-Yuan. Closing this issue.
