### ISSUE TITLE
intent labels

### ISSUE THREAD

**Issue by kpe** [mesnilgr/is13#33]
I wondering where to download an ATIS dataset including the intent labels?
The 5 folds available at
 
http://lisaweb.iro.umontreal.ca/transfert/lisa/users/mesnilgr/atis/

does not include the intent labels, and the dropbox link seems to be no longer active.

I would be very grateful for any hint of how to obtain the ATIS dataset.

**Comment by incalia** [comment]
the intent labels have not been released.  i would recommend to get in touch with the authors from microsoft to access the dataset.

**Comment by kpe** [comment]
OK, thanks!

**Comment by kpe** [comment]
(just as an info) An ATIS dataset including the intent labels seems to be available in the MS CNTK; I have written a kind of a downloader at https://github.com/kpe/notebooks/blob/master/ms_cntk_atis_dataset_reader.ipynb

**Comment by mesnilgr** [comment]
I added a reference to your notebook in the README.  Thank you @kpe
