### ISSUE TITLE
conlleval.pl OSError: [WinError 193] %1 is not a valid Win32 application, FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by minump** [mesnilgr/is13#34]
Unable to run conlleval.pl even after downloading to code directory.
Errors :
  File "C:\AppData\Local\Continuum\anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)

OSError: [WinError 193] %1 is not a valid Win32 application

  File "C:\AppData\Local\Continuum\anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by mesnilgr** [comment]
Have you given execution permission to conlleval.pl?  This should solve your problem.
