### ISSUE TITLE
Link for ATIS dataset not working again

### ISSUE THREAD

**Issue by Halleyawoo** [mesnilgr/is13#35]
Hello！
Very nice work. 
Can u give a valid link for this dataset? Thank u very much!

**Comment by mesnilgr** [comment]
Apologies for the delay.

https://www.dropbox.com/s/81ar3d2ck3yavic/atis.fold1.pkl.gz?dl=0

Unfortunately, I was only able to recover the fold 1 of the dataset since the university deleted my account where all the different folds were stored.

Hope this helps,

Grégoire

**Comment by mesnilgr** [comment]
I found the fold 3 as well.  Maybe other people can share links here for other folds:

https://www.dropbox.com/s/tinjzm1b22tozn8/atis.fold3.pkl.gz?dl=0

Quick note, each fold contains the whole dataset.  Each fold corresponds to a different way to shuffle and split the training & validation set.

**Comment by mesnilgr** [comment]
https://github.com/mesnilgr/is13/commit/f25db1026d3b30d329992c803f793347164c371c

The code should now work with the new links.  Closing this issue.
