### ISSUE TITLE
ImportError: No module named is13.data

### ISSUE THREAD

**Issue by perellonieto** [mesnilgr/is13#4]
README.md - 
The two lines of code to run the examples do not work if you do not add your actual path into the PYTHONPATH variable.

```
git clone git@github.com:mesnilgr/is13.git
python is13/examples/elman-forward.py
```

Will throw the error:

```
Traceback (most recent call last):
  File "./is13/examples/elman-forward.py", line 8, in <module>
    from is13.data import load
ImportError: No module named is13.data
```

By default Python do not add your actual path in sys.path and you need to add it explicitly.
In case of Bash I solved the problem by running:

```
git clone git@github.com:mesnilgr/is13.git
export PYTHONPATH=${PYTHONPATH}:`pwd -P`
python is13/examples/elman-forward.py
```

This line adds your current path without following symbolic links.

I know that in every Shell and Operating System the solution can be a different procedure, for that reason, I think you could just indicate that it is necessary to add your actual path in the variable PYTHONPATH.

**Comment by mesnilgr** [comment]
fixed
