### ISSUE TITLE
ImportError: No module named is13.data

### ISSUE THREAD

**Issue by andyyuan78** [mesnilgr/is13#6]
/home/ubgpu/github/is13:/usr/local/lib/python2.7/dist-packages
ubgpu@ubgpu:~/github/is13$ 

ubgpu@ubgpu:~/github/is13$ python examples/elman-forward.py
Traceback (most recent call last):
  File "examples/elman-forward.py", line 8, in <module>
    from is13.data import load
ImportError: No module named is13.data
ubgpu@ubgpu:~/github/is13$

**Comment by mesnilgr** [comment]
from the README:
In order to reproduce the results, make sure Theano is installed and the repository is in your PYTHONPATH, e.g run the command export PYTHONPATH=/path/where/is13/is:$PYTHONPATH

in your case:
export PYTHONPATH=~/github:$PYTHONPATH

**Comment by andyyuan78** [comment]
ubgpu@ubgpu:~/github/is13$ sudo python examples/elman-forward.py
[sudo] password for ubgpu: 
Traceback (most recent call last):
  File "examples/elman-forward.py", line 8, in <module>
    from is13.data import load
ImportError: No module named is13.data
ubgpu@ubgpu:~/github/is13$ export PYTHONPATH=~/github/is13:$PYTHONPATH
ubgpu@ubgpu:~/github/is13$ sudo python examples/elman-forward.py
Traceback (most recent call last):
  File "examples/elman-forward.py", line 8, in <module>
    from is13.data import load
ImportError: No module named is13.data
ubgpu@ubgpu:~/github/is13$ echo $PYTHONPATH
/home/ubgpu/github/is13:/home/ubgpu/github:/usr/local/lib/python2.7/dist-packages
ubgpu@ubgpu:~/github/is13$

**Comment by mesnilgr** [comment]
I wrote 
export PYTHONPATH=~/github:$PYTHONPATH

not what you typed:
export PYTHONPATH=~/github/is13:$PYTHONPATH

**Comment by andyyuan78** [comment]
sure, i try this first, it doesn't work; then add the path with is13/

ubgpu@ubgpu:~/github/is13$ export PYTHONPATH=~/github:$PYTHONPATH

ubgpu@ubgpu:~/github/is13$ sudo python examples/elman-forward.py
[sudo] password for ubgpu: 
Traceback (most recent call last):
  File "examples/elman-forward.py", line 8, in <module>
    from is13.data import load
ImportError: No module named is13.data
ubgpu@ubgpu:~/github/is13$

**Comment by andyyuan78** [comment]
I figure it out!

since I must use the sudo to run theano, but the $PYTHONPYTHON is not set with root

root@ubgpu:/home/ubgpu/github/is13# export PYTHONPATH=/home/ubgpu/github:/usr/local/lib/python2.7/dist-package

root@ubgpu:/home/ubgpu/github/is13# python examples/elman-forward.py
Downloading data from http://www-etud.iro.umontreal.ca/~mesnilgr/atis/atis.fold3.pkl.gz
/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py:293: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility
  rval = **import**(module_name, {}, {}, [module_name])

**Comment by lucas0** [comment]
Can you please explain what have you done to fix this? Im in windows and having the same problem "No module named is13.data"

**Comment by andyyuan78** [comment]
to lucas0 
the issue i got is under Ubuntu, as the 'root'  have a differen ENVIRONMENT VARIABLE with normal user.
